-- =============================================================================
-- Ubuntu Pools — Phase 1: Ledger + Event Foundations
-- Migration: 0001_phase1_foundation.sql
--
-- Governance Charter Compliance:
--   - Append-only: NO DELETE, NO UPDATE on immutable tables
--   - Double-entry: journal_entries enforced via CHECK constraints
--   - All monetary values: integer minor units (e.g. cents, satoshis)
--   - Event hashing: SHA-256 stored for auditability
--   - DB-level constraints are the enforcement layer, not application code
-- =============================================================================

-- ---------------------------------------------------------------------------
-- EXTENSION: pgcrypto for server-side SHA-256 hashing
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------------------------------------------------------------------------
-- ENUM: event_status
-- Tracks the lifecycle of an event record.
-- 'pending'   — emitted but not yet posted to ledger
-- 'posted'    — journal entries have been created
-- 'failed'    — posting failed; event is retained for audit
-- ---------------------------------------------------------------------------
CREATE TYPE event_status AS ENUM ('pending', 'posted', 'failed');

-- ---------------------------------------------------------------------------
-- ENUM: account_type
-- Standard double-entry account classification.
-- ---------------------------------------------------------------------------
CREATE TYPE account_type AS ENUM (
  'asset',
  'liability',
  'equity',
  'revenue',
  'expense'
);

-- ---------------------------------------------------------------------------
-- ENUM: entry_side
-- Debit or credit side of a journal entry.
-- ---------------------------------------------------------------------------
CREATE TYPE entry_side AS ENUM ('debit', 'credit');

-- ---------------------------------------------------------------------------
-- TABLE: events
--
-- The immutable, append-only event log.
-- Every state change in the system MUST produce a row here.
--
-- Immutability enforcement:
--   - No application-level DELETE or UPDATE is permitted.
--   - Row-level security (Phase 2) will enforce this at DB level.
--   - The 'hash' column is a deterministic SHA-256 of the canonical payload.
--   - 'prev_hash' chains events for tamper-evidence (hash chain).
--
-- Columns:
--   id          — UUID primary key, generated by DB
--   event_type  — namespaced string, e.g. 'pool.created', 'member.joined'
--   actor_id    — UUID of the entity that caused this event (user, system)
--   entity_id   — UUID of the primary entity this event concerns
--   entity_type — string discriminator for entity_id (e.g. 'pool', 'member')
--   payload     — JSONB: structured event data (schema validated in app layer)
--   occurred_at — wall-clock time of event emission (UTC)
--   sequence_no — monotonically increasing per entity for ordering
--   hash        — SHA-256 of canonical event fields (deterministic)
--   prev_hash   — hash of the previous event for this entity (chain integrity)
--   status      — lifecycle state of this event
-- ---------------------------------------------------------------------------
CREATE TABLE events (
  id          UUID        NOT NULL DEFAULT gen_random_uuid(),
  event_type  TEXT        NOT NULL,
  actor_id    UUID        NOT NULL,
  entity_id   UUID        NOT NULL,
  entity_type TEXT        NOT NULL,
  payload     JSONB       NOT NULL DEFAULT '{}',
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  sequence_no BIGINT      NOT NULL,
  hash        TEXT        NOT NULL,
  prev_hash   TEXT,           -- NULL only for the first event of an entity
  status      event_status NOT NULL DEFAULT 'pending',

  -- Primary key
  CONSTRAINT events_pkey PRIMARY KEY (id),

  -- Hash must be non-empty
  CONSTRAINT events_hash_nonempty CHECK (hash <> ''),

  -- event_type must be namespaced (contains a dot)
  CONSTRAINT events_type_namespaced CHECK (event_type LIKE '%.%'),

  -- entity_type must be non-empty
  CONSTRAINT events_entity_type_nonempty CHECK (entity_type <> ''),

  -- sequence_no must be positive
  CONSTRAINT events_sequence_positive CHECK (sequence_no > 0),

  -- Unique hash per event (deterministic hashing guarantees no duplicates)
  CONSTRAINT events_hash_unique UNIQUE (hash),

  -- Unique sequence per entity (no gaps enforced at app layer)
  CONSTRAINT events_entity_sequence_unique UNIQUE (entity_id, sequence_no)
);

-- Index: fast lookup by entity
CREATE INDEX idx_events_entity ON events (entity_id, sequence_no ASC);

-- Index: fast lookup by actor
CREATE INDEX idx_events_actor ON events (actor_id, occurred_at DESC);

-- Index: fast lookup by type
CREATE INDEX idx_events_type ON events (event_type, occurred_at DESC);

-- Index: status for processing queues
CREATE INDEX idx_events_status ON events (status) WHERE status = 'pending';

-- ---------------------------------------------------------------------------
-- TABLE: ledger_accounts
--
-- Chart of accounts for the double-entry ledger.
-- Accounts are created once and never deleted.
--
-- Columns:
--   id           — UUID primary key
--   code         — human-readable account code (e.g. 'POOL-001-ASSET')
--   name         — descriptive name
--   account_type — asset/liability/equity/revenue/expense
--   currency     — ISO 4217 currency code (e.g. 'USD', 'ZAR')
--   entity_id    — optional: links account to a specific entity (pool, member)
--   entity_type  — discriminator for entity_id
--   created_at   — immutable creation timestamp
--   created_by_event_id — the event that caused this account to be opened
-- ---------------------------------------------------------------------------
CREATE TABLE ledger_accounts (
  id                  UUID        NOT NULL DEFAULT gen_random_uuid(),
  code                TEXT        NOT NULL,
  name                TEXT        NOT NULL,
  account_type        account_type NOT NULL,
  currency            CHAR(3)     NOT NULL,
  entity_id           UUID,
  entity_type         TEXT,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by_event_id UUID        NOT NULL,

  -- Primary key
  CONSTRAINT ledger_accounts_pkey PRIMARY KEY (id),

  -- Account code must be unique
  CONSTRAINT ledger_accounts_code_unique UNIQUE (code),

  -- Currency must be 3 uppercase letters
  CONSTRAINT ledger_accounts_currency_format CHECK (currency ~ '^[A-Z]{3}$'),

  -- Name must be non-empty
  CONSTRAINT ledger_accounts_name_nonempty CHECK (name <> ''),

  -- entity_id and entity_type must both be present or both absent
  CONSTRAINT ledger_accounts_entity_consistency
    CHECK (
      (entity_id IS NULL AND entity_type IS NULL) OR
      (entity_id IS NOT NULL AND entity_type IS NOT NULL)
    ),

  -- Foreign key to events (account must be created by a real event)
  CONSTRAINT ledger_accounts_event_fk
    FOREIGN KEY (created_by_event_id) REFERENCES events (id)
);

-- Index: lookup by entity
CREATE INDEX idx_ledger_accounts_entity ON ledger_accounts (entity_id, entity_type)
  WHERE entity_id IS NOT NULL;

-- Index: lookup by type
CREATE INDEX idx_ledger_accounts_type ON ledger_accounts (account_type, currency);

-- ---------------------------------------------------------------------------
-- TABLE: journal_entries
--
-- The immutable double-entry ledger.
-- Every financial movement is recorded as a pair of entries (debit + credit)
-- that MUST balance to zero within a transaction_id.
--
-- Immutability enforcement:
--   - No DELETE, no UPDATE.
--   - Corrections are made via reversing entries (new rows).
--   - The balance constraint is enforced by the posting engine at app layer
--     and verified by the ledger_balance_check view.
--
-- Columns:
--   id             — UUID primary key
--   transaction_id — groups the debit/credit pair(s) for one economic event
--   event_id       — the event that caused this journal entry
--   account_id     — which ledger account is affected
--   side           — 'debit' or 'credit'
--   amount         — integer minor units (MUST be > 0)
--   currency       — must match the account's currency
--   description    — human-readable memo
--   posted_at      — when this entry was written to the ledger
--   sequence_no    — ordering within a transaction
-- ---------------------------------------------------------------------------
CREATE TABLE journal_entries (
  id             UUID        NOT NULL DEFAULT gen_random_uuid(),
  transaction_id UUID        NOT NULL,
  event_id       UUID        NOT NULL,
  account_id     UUID        NOT NULL,
  side           entry_side  NOT NULL,
  amount         BIGINT      NOT NULL,
  currency       CHAR(3)     NOT NULL,
  description    TEXT        NOT NULL DEFAULT '',
  posted_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  sequence_no    INT         NOT NULL,

  -- Primary key
  CONSTRAINT journal_entries_pkey PRIMARY KEY (id),

  -- Amount must be strictly positive (zero-value entries are meaningless)
  CONSTRAINT journal_entries_amount_positive CHECK (amount > 0),

  -- Currency must be 3 uppercase letters
  CONSTRAINT journal_entries_currency_format CHECK (currency ~ '^[A-Z]{3}$'),

  -- sequence_no must be positive
  CONSTRAINT journal_entries_sequence_positive CHECK (sequence_no > 0),

  -- Foreign key to events
  CONSTRAINT journal_entries_event_fk
    FOREIGN KEY (event_id) REFERENCES events (id),

  -- Foreign key to ledger_accounts
  CONSTRAINT journal_entries_account_fk
    FOREIGN KEY (account_id) REFERENCES ledger_accounts (id),

  -- Unique entry per account per transaction sequence
  CONSTRAINT journal_entries_txn_seq_unique
    UNIQUE (transaction_id, account_id, sequence_no)
);

-- Index: fast lookup by transaction (to verify balance)
CREATE INDEX idx_journal_entries_txn ON journal_entries (transaction_id, sequence_no ASC);

-- Index: fast lookup by event
CREATE INDEX idx_journal_entries_event ON journal_entries (event_id);

-- Index: account history (for balance calculation)
CREATE INDEX idx_journal_entries_account ON journal_entries (account_id, posted_at ASC);

-- ---------------------------------------------------------------------------
-- TABLE: posting_rules
--
-- Defines which event types trigger which ledger postings.
-- This is the configuration layer for the journal posting engine.
--
-- A posting rule maps:
--   event_type → (debit_account_pattern, credit_account_pattern, amount_path)
--
-- Columns:
--   id                    — UUID primary key
--   event_type            — the event type this rule applies to
--   rule_name             — human-readable name
--   debit_account_code    — account code to debit (supports {entity_id} template)
--   credit_account_code   — account code to credit (supports {entity_id} template)
--   amount_payload_path   — JSONPath into event.payload to extract amount
--   currency_payload_path — JSONPath into event.payload to extract currency
--   description_template  — template for journal entry description
--   is_active             — soft-disable without deletion (rules are config, not data)
--   created_at            — immutable creation timestamp
--   created_by_event_id   — the event that created this rule
--   version               — incremented when rule is superseded (new row created)
-- ---------------------------------------------------------------------------
CREATE TABLE posting_rules (
  id                    UUID        NOT NULL DEFAULT gen_random_uuid(),
  event_type            TEXT        NOT NULL,
  rule_name             TEXT        NOT NULL,
  debit_account_code    TEXT        NOT NULL,
  credit_account_code   TEXT        NOT NULL,
  amount_payload_path   TEXT        NOT NULL,
  currency_payload_path TEXT        NOT NULL,
  description_template  TEXT        NOT NULL DEFAULT '',
  is_active             BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by_event_id   UUID        NOT NULL,
  version               INT         NOT NULL DEFAULT 1,

  -- Primary key
  CONSTRAINT posting_rules_pkey PRIMARY KEY (id),

  -- event_type must be namespaced
  CONSTRAINT posting_rules_type_namespaced CHECK (event_type LIKE '%.%'),

  -- Account codes must be non-empty
  CONSTRAINT posting_rules_debit_nonempty CHECK (debit_account_code <> ''),
  CONSTRAINT posting_rules_credit_nonempty CHECK (credit_account_code <> ''),

  -- Amount path must be non-empty
  CONSTRAINT posting_rules_amount_path_nonempty CHECK (amount_payload_path <> ''),

  -- Version must be positive
  CONSTRAINT posting_rules_version_positive CHECK (version > 0),

  -- Foreign key to events
  CONSTRAINT posting_rules_event_fk
    FOREIGN KEY (created_by_event_id) REFERENCES events (id)
);

-- Index: fast lookup by event type (for posting engine)
CREATE INDEX idx_posting_rules_event_type ON posting_rules (event_type)
  WHERE is_active = TRUE;

-- ---------------------------------------------------------------------------
-- VIEW: v_account_balances
--
-- Computes the running balance for each account.
-- Debit-normal accounts (asset, expense): balance = debits - credits
-- Credit-normal accounts (liability, equity, revenue): balance = credits - debits
--
-- This view is READ-ONLY and derived entirely from journal_entries.
-- It is NOT authoritative state — the journal_entries table is.
-- ---------------------------------------------------------------------------
CREATE VIEW v_account_balances AS
SELECT
  la.id           AS account_id,
  la.code         AS account_code,
  la.name         AS account_name,
  la.account_type,
  la.currency,
  la.entity_id,
  la.entity_type,
  COALESCE(SUM(
    CASE
      WHEN je.side = 'debit'  THEN  je.amount
      WHEN je.side = 'credit' THEN -je.amount
    END
  ), 0) AS raw_balance,
  -- Normalized balance: positive = normal balance for account type
  COALESCE(SUM(
    CASE la.account_type
      WHEN 'asset'     THEN CASE WHEN je.side = 'debit'  THEN  je.amount ELSE -je.amount END
      WHEN 'expense'   THEN CASE WHEN je.side = 'debit'  THEN  je.amount ELSE -je.amount END
      WHEN 'liability' THEN CASE WHEN je.side = 'credit' THEN  je.amount ELSE -je.amount END
      WHEN 'equity'    THEN CASE WHEN je.side = 'credit' THEN  je.amount ELSE -je.amount END
      WHEN 'revenue'   THEN CASE WHEN je.side = 'credit' THEN  je.amount ELSE -je.amount END
    END
  ), 0) AS normal_balance,
  COUNT(je.id) AS entry_count,
  MAX(je.posted_at) AS last_posted_at
FROM ledger_accounts la
LEFT JOIN journal_entries je ON je.account_id = la.id
GROUP BY
  la.id, la.code, la.name, la.account_type, la.currency, la.entity_id, la.entity_type;

-- ---------------------------------------------------------------------------
-- VIEW: v_transaction_balance_check
--
-- Verifies that every transaction_id has balanced debits and credits.
-- Any row where debit_total != credit_total indicates a posting error.
-- This view is used by the posting engine's integrity check.
-- ---------------------------------------------------------------------------
CREATE VIEW v_transaction_balance_check AS
SELECT
  transaction_id,
  event_id,
  currency,
  SUM(CASE WHEN side = 'debit'  THEN amount ELSE 0 END) AS debit_total,
  SUM(CASE WHEN side = 'credit' THEN amount ELSE 0 END) AS credit_total,
  SUM(CASE WHEN side = 'debit'  THEN amount ELSE 0 END) -
  SUM(CASE WHEN side = 'credit' THEN amount ELSE 0 END) AS imbalance,
  COUNT(*) AS entry_count
FROM journal_entries
GROUP BY transaction_id, event_id, currency;

-- ---------------------------------------------------------------------------
-- FUNCTION: assert_transaction_balanced(p_transaction_id UUID)
--
-- Raises an exception if the given transaction is not balanced.
-- Called by the posting engine after inserting journal entries.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION assert_transaction_balanced(p_transaction_id UUID)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
  v_imbalance BIGINT;
  v_currency  CHAR(3);
BEGIN
  SELECT imbalance, currency
  INTO v_imbalance, v_currency
  FROM v_transaction_balance_check
  WHERE transaction_id = p_transaction_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Transaction % not found in journal_entries', p_transaction_id;
  END IF;

  IF v_imbalance <> 0 THEN
    RAISE EXCEPTION
      'Transaction % is unbalanced: imbalance = % %',
      p_transaction_id, v_imbalance, v_currency;
  END IF;
END;
$$;

-- ---------------------------------------------------------------------------
-- FUNCTION: get_account_balance(p_account_id UUID)
--
-- Returns the normal balance for an account as of now.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION get_account_balance(p_account_id UUID)
RETURNS BIGINT
LANGUAGE sql
STABLE
AS $$
  SELECT normal_balance
  FROM v_account_balances
  WHERE account_id = p_account_id;
$$;

-- ---------------------------------------------------------------------------
-- TRIGGER FUNCTION: prevent_event_mutation()
--
-- Prevents UPDATE or DELETE on the events table.
-- Immutability is enforced at the database level.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION prevent_event_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION
      'IMMUTABILITY VIOLATION: DELETE on events table is forbidden. Event ID: %',
      OLD.id;
  END IF;

  IF TG_OP = 'UPDATE' THEN
    -- Only allow status transitions (pending → posted, pending → failed)
    -- All other fields are immutable
    IF OLD.id             <> NEW.id             OR
       OLD.event_type     <> NEW.event_type     OR
       OLD.actor_id       <> NEW.actor_id       OR
       OLD.entity_id      <> NEW.entity_id      OR
       OLD.entity_type    <> NEW.entity_type    OR
       OLD.payload::text  <> NEW.payload::text  OR
       OLD.occurred_at    <> NEW.occurred_at    OR
       OLD.sequence_no    <> NEW.sequence_no    OR
       OLD.hash           <> NEW.hash           OR
       COALESCE(OLD.prev_hash, '') <> COALESCE(NEW.prev_hash, '')
    THEN
      RAISE EXCEPTION
        'IMMUTABILITY VIOLATION: Core fields of event % cannot be modified. Only status transitions are permitted.',
        OLD.id;
    END IF;

    -- Validate status transition
    IF OLD.status = 'posted' THEN
      RAISE EXCEPTION
        'IMMUTABILITY VIOLATION: Event % is already posted and cannot be re-transitioned.',
        OLD.id;
    END IF;

    IF OLD.status = 'failed' AND NEW.status <> 'failed' THEN
      RAISE EXCEPTION
        'IMMUTABILITY VIOLATION: Event % is in failed state and cannot be re-transitioned.',
        OLD.id;
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

-- Attach trigger to events table
CREATE TRIGGER trg_events_immutability
  BEFORE UPDATE OR DELETE ON events
  FOR EACH ROW
  EXECUTE FUNCTION prevent_event_mutation();

-- ---------------------------------------------------------------------------
-- TRIGGER FUNCTION: prevent_journal_mutation()
--
-- Prevents any UPDATE or DELETE on journal_entries.
-- Journal entries are permanently immutable once written.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION prevent_journal_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION
      'IMMUTABILITY VIOLATION: DELETE on journal_entries is forbidden. Entry ID: %',
      OLD.id;
  END IF;

  IF TG_OP = 'UPDATE' THEN
    RAISE EXCEPTION
      'IMMUTABILITY VIOLATION: UPDATE on journal_entries is forbidden. Entry ID: %',
      OLD.id;
  END IF;

  RETURN NEW;
END;
$$;

-- Attach trigger to journal_entries table
CREATE TRIGGER trg_journal_entries_immutability
  BEFORE UPDATE OR DELETE ON journal_entries
  FOR EACH ROW
  EXECUTE FUNCTION prevent_journal_mutation();

-- ---------------------------------------------------------------------------
-- TRIGGER FUNCTION: prevent_account_mutation()
--
-- Prevents DELETE on ledger_accounts.
-- Accounts can never be removed; they can only be superseded.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION prevent_account_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION
      'IMMUTABILITY VIOLATION: DELETE on ledger_accounts is forbidden. Account ID: %',
      OLD.id;
  END IF;

  -- Allow updates only to non-identifying fields (name, is_active in future)
  IF TG_OP = 'UPDATE' THEN
    IF OLD.id           <> NEW.id           OR
       OLD.code         <> NEW.code         OR
       OLD.account_type <> NEW.account_type OR
       OLD.currency     <> NEW.currency     OR
       COALESCE(OLD.entity_id::text, '') <> COALESCE(NEW.entity_id::text, '') OR
       COALESCE(OLD.entity_type, '') <> COALESCE(NEW.entity_type, '') OR
       OLD.created_at   <> NEW.created_at   OR
       OLD.created_by_event_id <> NEW.created_by_event_id
    THEN
      RAISE EXCEPTION
        'IMMUTABILITY VIOLATION: Identifying fields of ledger_account % cannot be modified.',
        OLD.id;
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

-- Attach trigger to ledger_accounts table
CREATE TRIGGER trg_ledger_accounts_immutability
  BEFORE UPDATE OR DELETE ON ledger_accounts
  FOR EACH ROW
  EXECUTE FUNCTION prevent_account_mutation();

-- ---------------------------------------------------------------------------
-- COMMENTS: Table and column documentation
-- ---------------------------------------------------------------------------
COMMENT ON TABLE events IS
  'Append-only event log. Every state change in Ubuntu Pools emits a row here. '
  'No DELETE or UPDATE of core fields is permitted. '
  'Only status transitions (pending→posted, pending→failed) are allowed.';

COMMENT ON TABLE ledger_accounts IS
  'Chart of accounts for the double-entry ledger. '
  'Accounts are created once and never deleted. '
  'All monetary values are in integer minor units.';

COMMENT ON TABLE journal_entries IS
  'Immutable double-entry ledger. '
  'Every financial movement is a debit/credit pair tied to an event. '
  'Corrections are made via reversing entries (new rows), never by mutation.';

COMMENT ON TABLE posting_rules IS
  'Configuration table mapping event types to ledger posting patterns. '
  'Used by the journal posting engine to determine which accounts to debit/credit.';

COMMENT ON VIEW v_account_balances IS
  'Derived view of account balances. NOT authoritative — journal_entries is the source of truth.';

COMMENT ON VIEW v_transaction_balance_check IS
  'Integrity check view. Any row with imbalance != 0 indicates a posting error.';
