#!/bin/bash
# DNS Configuration Script for Venture Vision Ubuntu
# Add these A records to your domain registrar

echo "🌐 DNS Configuration for Venture Vision Ubuntu"
echo "=============================================="
echo ""
echo "🔍 DOMAIN STATUS: venturevisionubuntu.co.za"
echo "   Registrar: HOSTAFRICA"
echo "   Nameservers: ns1.host-ww.net, ns2.host-ww.net, ns3.host-ww.net, ns4.host-ww.net"
echo "   Status: Active (created 2026-04-24)"
echo ""
echo "📋 REQUIRED DNS CONFIGURATION:"
echo "Log into your HOSTAFRICA control panel and navigate to DNS management."
echo ""
echo "Add these A records:"
echo ""
echo "1. For venturevisionubuntu.co.za:"
echo "   Type: A"
echo "   Name: @ (or leave blank)"
echo "   Value: 76.76.21.21"
echo "   TTL: 300 (5 minutes)"
echo ""
echo "2. For api.venturevisionubuntu.co.za:"
echo "   Type: A"
echo "   Name: api"
echo "   Value: 76.76.21.21"
echo "   TTL: 300 (5 minutes)"
echo ""
echo "🔗 HOSTAFRICA Login:"
echo "   https://www.hostafrica.co.za/clientarea.php"
echo ""
echo "📍 Navigation:"
echo "   1. Login to client area"
echo "   2. Go to 'Domains' → 'My Domains'"
echo "   3. Click on venturevisionubuntu.co.za"
echo "   4. Go to 'DNS Management' or 'Nameservers & DNS'"
echo "   5. Add the A records above"
echo "   6. Save changes"
echo ""
echo "⏳ After adding records:"
echo "   - Wait 5-15 minutes for DNS propagation"
echo "   - Run: npm run final:verify"
echo ""
echo "✅ SUCCESS INDICATORS:"
echo "   curl https://venturevisionubuntu.co.za → HTTP 200"
echo "   curl https://api.venturevisionubuntu.co.za/health → HTTP 200"