import type { GameId, GameDefinition } from './types';
 
export const GAME_DEFINITIONS: Record<GameId, GameDefinition> = {
  ubuntu_monopoly: {
    id:           'ubuntu_monopoly',
    name:         'Ubuntu Monopoly',
    tagline:      'Collective ownership beats individual hoarding',
    description:  'A collectivised reimagining of the classic property game. Rent income pools into a shared village fund. Syndicates outperform monopolies. The maths of Ubuntu in motion.',
    concepts:     ['Asset accumulation', 'Collective ownership', 'Compound returns', 'Leverage', 'Syndication'],
    signals:      ['risk_appetite', 'cooperative_quotient'],
    minPlayers:   1, maxPlayers: 4,
    estimatedMins: 30,
    difficulty:   'intermediate',
    icon:         '🏘️',
    color:        '#2E6B4A',
  },
  pool_simulator: {
    id:           'pool_simulator',
    name:         'Pool Simulator',
    tagline:      'Manage a real ROSCA through real stress',
    description:  'You are the pool administrator. Eight members, twelve months, unpredictable life events. Every governance decision has second-order consequences.',
    concepts:     ['ROSCA mechanics', 'Pool health', 'Default risk', 'Emergency protocols', 'Member trust'],
    signals:      ['stress_response', 'leadership_index'],
    minPlayers:   1, maxPlayers: 1,
    estimatedMins: 20,
    difficulty:   'advanced',
    icon:         '🫙',
    color:        '#1B3A2D',
  },
  credit_ladder: {
    id:           'credit_ladder',
    name:         'Credit Ladder',
    tagline:      'Climb the credit score. Beat the interest.',
    description:  'A card game where your hand is your financial obligations. Interest compounds every turn. Minimum payments are a trap. Learn this before it costs you real money.',
    concepts:     ['Interest compounding', 'Credit scoring', 'Debt management', 'Repayment priority'],
    signals:      ['overextension', 'risk_appetite'],
    minPlayers:   1, maxPlayers: 1,
    estimatedMins: 15,
    difficulty:   'beginner',
    icon:         '🃏',
    color:        '#8B3A2A',
  },
  the_commons: {
    id:           'the_commons',
    name:         'The Commons',
    tagline:      'Over-extract and everyone loses. Share and it grows.',
    description:  'A multiplayer resource game where the shared pool regenerates if not over-exploited. Trust infrastructure is the only thing that makes cooperation durable.',
    concepts:     ['Tragedy of the commons', 'Cooperative resource management', 'Free-rider detection', 'Trust infrastructure'],
    signals:      ['cooperative_quotient', 'leadership_index'],
    minPlayers:   1, maxPlayers: 6,
    estimatedMins: 25,
    difficulty:   'intermediate',
    icon:         '🌱',
    color:        '#C8962B',
  },
  market_maker: {
    id:           'market_maker',
    name:         'Market Maker',
    tagline:      'Buy together. Pay less. Grow more.',
    description:  'Aggregate demand, negotiate with suppliers, close bulk procurement deals under time pressure. A direct mirror of the CPME system.',
    concepts:     ['Procurement leverage', 'Bulk buying', 'Supply and demand', 'Negotiation', 'CPME mechanics'],
    signals:      ['overextension', 'cooperative_quotient'],
    minPlayers:   1, maxPlayers: 1,
    estimatedMins: 20,
    difficulty:   'intermediate',
    icon:         '🛒',
    color:        '#2E6B4A',
  },
};
