apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lindiwe-ai-dev
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: ubuntu-pools
    component: lindiwe-ai
    environment: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/divhanimajokweni-ctrl/ubuntu-pools
    targetRevision: develop
    path: argo
    directory:
      include: "lindiwe-api.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: up-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
